service: ms1-service
runtime: java
env: flex

handlers:
-  url: /.*
   script: this field is required , bu ignored
runtime_config:
  jdk: openjdk8
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100